#!/bin/bash

S="${BASH_SOURCE[0]}"
D=`dirname "$S"`
LIBSIGN_ROOT="`cd "$D"/.. && pwd`"

echo "LIBSIGN_ROOT=$LIBSIGN_ROOT"

cmd="LD_LIBRARY_PATH=$LIBSIGN_ROOT/src/lib $LIBSIGN_ROOT/src/selsign/selsign"
cmd_opts=""
out=".p7a"

while [ $# -gt 0 ]; do
    case "$1" in
    --detached)
        cmd_opts=$cmd_opts" -d"
        out=".p7s"
        ;;
    *)
        break
        ;;
    esac
    shift
done

[ -z "$1" -o ! -f "$1" ] && {
    eval "$cmd"
    exit 1
}

eval "$cmd $cmd_opts $1"

out="$1"$out

[ $? -eq 0 -a -s "$out" ] &&
    openssl pkcs7 -in "$out" -inform DER -print -text -noout
